version: '3.1'

services:
  postgresqldb:
    image: postgres:latest
    container_name: postgresqldb
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fresh
      POSTGRES_DB: portfolio
  redisdb:
    image: "redis"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes