version: '3.1'

services:
  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fresh
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
  admin:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
