version: '3.1'

services:
  postgresdb:
    image: postgres:13-alpine
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fresh
      POSTGRES_DB: dilim
    ports:
      - "5432:5432"